### ISSUE TITLE
Helm extension for perspeen

### ISSUE THREAD

**Issue by jimo1001** [seudut/perspeen#10]
"perspeen" is a very cool elisp package!
I created a [helm](https://github.com/emacs-helm/helm/) extension for perspeen, May I register the melpa?
https://github.com/jimo1001/helm-perspeen

Thanks.

**Comment by seudut** [comment]
I am glad to see that perspeen is integrated with helm. Thanks for your work. feel free to register it into melpa.
Thanks.

**Comment by jimo1001** [comment]
Thank you for your response!
some time ago, I created a pull request to melpa.
https://github.com/melpa/melpa/pull/4541
